export const ROUTE_PATHS = {
  root: "/",
  dashboard: "/dashboard",
  dashboardProductsNew: "/dashboard/products/new",
  dashboardCategories: "/dashboard/catalog/categories",
  dashboardBrands: "/dashboard/catalog/brands",
  dashboardUnits: "/dashboard/catalog/units",
  dashboardBarcodes: "/dashboard/catalog/barcodes",
  dashboardStock: "/dashboard/inventory/stock",
  dashboardMovements: "/dashboard/inventory/movements",
  dashboardAdjustments: "/dashboard/inventory/adjustments",
  dashboardSuppliers: "/dashboard/purchases/suppliers",
  dashboardPurchaseOrders: "/dashboard/purchases/orders",
  dashboardReceptions: "/dashboard/purchases/receptions",
  dashboardOrders: "/dashboard/sales/orders",
  dashboardInvoices: "/dashboard/sales/invoices",
  dashboardInventoryReport: "/dashboard/reports/inventory",
  dashboardSalesReport: "/dashboard/reports/sales",
  dashboardPurchasesReport: "/dashboard/reports/purchases",
  dashboardWarehouses: "/dashboard/settings/warehouses",
  dashboardUsers: "/dashboard/settings/users",
  dashboardRoles: "/dashboard/settings/roles",
  dashboardCustomers: "/dashboard/customers",
  cliente: "/cliente",
  registerCustomer: "/register-customer",
} as const;

export const PROTECTED_ROUTE_PATHS = {
  dashboard: "dashboard",
  dashboardProductsNew: "dashboard/products/new",
  dashboardAdminSection: "dashboard/:section/*",
  dashboardCustomers: "dashboard/customers",
  cliente: "cliente",
} as const;
